10011	FAIL	Cookie sem flag Secure
10015	FAIL	Pagina insegura
10017	WARN	Redirect para URL diferente
10021	WARN	X-Frame-Options em falta
10049	WARN	Pagina contem sink de XSS
10050	WARN	Conteudo obtido de cache
10063	WARN	X-XSS-Protection em falta
10064	WARN	Referrer-Policy em falta
10069	WARN	Source disclosure
10096	WARN	Directory browsing
10098	WARN	Cross-domain misconfiguration
10202	WARN	Ausencia de tokens anti-CSRF
2	WARN	CSP em falta
3	WARN	Referrer-Policy em falta
